### ISSUE TITLE
setup.md: how download data into LSIT VM?

### ISSUE THREAD

**Issue by JamesFrew** [UCSBCarpentry/2023-05-16-ucsb-python#1]
In setup.md, students are instructed to download the data files. How exactly are they supposed to do this from within JupyterLab?

**Comment by srerickson** [comment]
Great question! I'll add instructions for prepping the data in JupyterLab

**Comment by srerickson** [comment]
I've decided to do the data upload to Jupyter Lab in the class rather than expect everyone to do it beforehand. Closing this.
